apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kustomize

namespace: demo-java-app
images:
  - name: renovate-talk-java-demo-app
    newName: renovatetalkacr.azurecr.io/renovate-talk-java-demo-app
    newTag: 1.7.0
