apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/deployment.yaml
  - resources/ingress.yaml
  - resources/ns.yaml
  - resources/service.yaml

namespace: demo-java-app
images:
  - name: 930970667460.dkr.ecr.eu-west-1.amazonaws.com/renovate-talk-java-demo-app
    newTag: 1.5.1
