apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../kustomize

images:
  - name: renovate-talk-java-demo-app
    newName: 930970667460.dkr.ecr.eu-west-1.amazonaws.com/renovate-talk-java-demo-app
